fn main() {
    // Application commands do not receive an ACL entry unless they are
    // declared here. Keep this list in lockstep with `generate_handler!` so
    // capabilities can grant a command to one WebView without implicitly
    // granting it to every window in the application.
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new().commands(&[
            "get_app_snapshot",
            "desktop_displays",
            "set_interaction_enabled",
            "select_backend",
            "dispatch_app_action",
            "publish_settings",
            "lite_settings_get",
            "lite_settings_save",
            "lite_image_import",
            "lite_image_resolve",
            "set_desktop_wallpaper_fallback",
            "desktop_wallpaper_fallback_status",
            "notify_appearance_changed",
            "set_lock_screen_enabled",
            "clear_stale_lock_screen_backup",
            "get_lock_screen_diagnostics",
            "set_autostart",
            "autostart_status",
            "scan_dsh_paths",
            // Lists the harness execution subjects (shells with their own
            // checkout, and source trees) the shim can offer and start.
            "scan_harness_targets",
            // Starts the chosen execution subject (a shell, or a source tree) and
            // the unattended counterpart of that start.
            "launch_harness_target",
            // Idempotent 「拉起 UI」: start the subject if it is gone, show a window
            // the wallpaper hid, then bring it forward.
            "ensure_harness_ui",
            "autostart_harness_target",
            "launch_dsh",
            "autostart_managed_dsh",
            "managed_dsh_autostart_status",
            "managed_dsh_status",
            "stop_managed_dsh",
            "translucent_tb_status",
            "launch_translucent_tb",
            "open_translucent_tb_install",
            "open_windows_lock_screen_settings",
            "prompt_for_api_key",
            "show_deepseek_login",
            "native_bootstrap_generation",
            "release_native_bootstrap",
            "deepseek_web_ensure",
            "deepseek_web_status",
            "deepseek_web_history",
            "deepseek_web_adapter_config_status",
            "open_deepseek_web_adapter_config",
            "reset_deepseek_web_adapter_config",
            "open_settings_window",
            "start_settings_drag",
            "hide_settings_window",
            "begin_interaction_region_session",
            "update_interaction_regions",
            "desktop_layout_metrics",
            "send_chat",
            "cancel_chat",
            "connect_harness",
            "harness_history",
            "harness_presets",
            "harness_set_preset",
            "harness_controls",
            "harness_set_permission",
            // Verifies that the renderer's island pointerdown is a real user click before any
            // keyboard handover may act on it (repair plan 3.A).
            "verify_island_click",
            "api_history",
            "list_api_conversations",
            "delete_api_conversation",
            "clear_api_history",
            "probe_harness",
            "scan_harness_endpoints_command",
            "set_harness_endpoint",
            "raise_client_window",
            "open_client_in_browser",
            "harness_endpoint_listening",
            "harness_endpoint_window",
            "appearance_get_state",
            "appearance_list_themes",
            "appearance_list_assets",
            "appearance_activate_theme",
            "appearance_set_override",
            "appearance_clear_override",
            "appearance_import_paths",
            "appearance_classify_asset",
            "appearance_export_current_theme",
            "appearance_resolve_asset",
            "appearance_resolve_library_asset",
        ]),
    ))
    .expect("failed to build Tauri application manifest")
}
